name: java-besu-plugins # title or short name for the stack (used on the website)
version: 0.1.0 # version of the stack
description: Hyperledger Besu Plugins # short description of this stack (used on the website and `list` command)
license: Apache-2.0 # license for the stack (SPDX license id)
language: java # language used for this stack
maintainers: # list of maintainers for this stack
  - name: Eric Lau
    email: ericglau@outlook.com
    github-id: ericglau
default-template: demo # folder name of default template
